// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AgencyRealEstate.API.Data.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Deal> Deals { get; set; }

    public virtual DbSet<DealDocument> DealDocuments { get; set; }

    public virtual DbSet<DealStatus> DealStatuses { get; set; }

    public virtual DbSet<DealType> DealTypes { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Property> Properties { get; set; }

    public virtual DbSet<PropertyOwner> PropertyOwners { get; set; }

    public virtual DbSet<PropertyPhoto> PropertyPhotos { get; set; }

    public virtual DbSet<PropertyStatus> PropertyStatuses { get; set; }

    public virtual DbSet<PropertyType> PropertyTypes { get; set; }

    public virtual DbSet<Showing> Showings { get; set; }

    public virtual DbSet<ShowingResult> ShowingResults { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserNotificationSetting> UserNotificationSettings { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<WallMaterial> WallMaterials { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Clients__E67E1A041D7E30F0");

            entity.HasIndex(e => e.UserId, "IX_Clients_UserID");

            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedByUserId).HasColumnName("CreatedByUserID");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PassportData).HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.Preferences).HasMaxLength(500);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ClientCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Clients_CreatedBy");

            entity.HasOne(d => d.User).WithMany(p => p.ClientUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Clients_User");
        });

        modelBuilder.Entity<Deal>(entity =>
        {
            entity.HasKey(e => e.DealId).HasName("PK__Deals__E5B2814681B3BAA0");

            entity.HasIndex(e => e.BuyerId, "IX_Deals_BuyerID");

            entity.HasIndex(e => e.PropertyId, "IX_Deals_PropertyID");

            entity.HasIndex(e => e.RealtorId, "IX_Deals_RealtorID");

            entity.HasIndex(e => e.SellerId, "IX_Deals_SellerID");

            entity.HasIndex(e => e.DealStatusId, "IX_Deals_Status");

            entity.HasIndex(e => e.DealTypeId, "IX_Deals_Type");

            entity.Property(e => e.DealId).HasColumnName("DealID");
            entity.Property(e => e.Amount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.BuyerId).HasColumnName("BuyerID");
            entity.Property(e => e.Commission).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedByUserId).HasColumnName("CreatedByUserID");
            entity.Property(e => e.DealStatusId)
                .HasDefaultValue((byte)1)
                .HasColumnName("DealStatusID");
            entity.Property(e => e.DealTypeId).HasColumnName("DealTypeID");
            entity.Property(e => e.PropertyId).HasColumnName("PropertyID");
            entity.Property(e => e.RealtorId).HasColumnName("RealtorID");
            entity.Property(e => e.SellerId).HasColumnName("SellerID");

            entity.HasOne(d => d.Buyer).WithMany(p => p.DealBuyers)
                .HasForeignKey(d => d.BuyerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deals_Buyer");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Deals)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deals_CreatedBy");

            entity.HasOne(d => d.DealStatus).WithMany(p => p.Deals)
                .HasForeignKey(d => d.DealStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deals_Status");

            entity.HasOne(d => d.DealType).WithMany(p => p.Deals)
                .HasForeignKey(d => d.DealTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deals_Type");

            entity.HasOne(d => d.Property).WithMany(p => p.Deals)
                .HasForeignKey(d => d.PropertyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deals_Property");

            entity.HasOne(d => d.Realtor).WithMany(p => p.Deals)
                .HasForeignKey(d => d.RealtorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deals_Realtor");

            entity.HasOne(d => d.Seller).WithMany(p => p.DealSellers)
                .HasForeignKey(d => d.SellerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Deals_Seller");
        });

        modelBuilder.Entity<DealDocument>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("PK__DealDocu__1ABEEF6FAC183F69");

            entity.HasIndex(e => e.DealId, "IX_DealDocuments_DealID");

            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.DealId).HasColumnName("DealID");
            entity.Property(e => e.DocumentName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UploadDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UploadedByUserId).HasColumnName("UploadedByUserID");

            entity.HasOne(d => d.Deal).WithMany(p => p.DealDocuments)
                .HasForeignKey(d => d.DealId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Documents_Deal");

            entity.HasOne(d => d.UploadedByUser).WithMany(p => p.DealDocuments)
                .HasForeignKey(d => d.UploadedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Documents_User");
        });

        modelBuilder.Entity<DealStatus>(entity =>
        {
            entity.HasKey(e => e.DealStatusId).HasName("PK__DealStat__1EE4551228E09561");

            entity.HasIndex(e => e.StatusName, "UQ__DealStat__05E7698ACA196EAA").IsUnique();

            entity.Property(e => e.DealStatusId).HasColumnName("DealStatusID");
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<DealType>(entity =>
        {
            entity.HasKey(e => e.DealTypeId).HasName("PK__DealType__1C7E20F6A4D2BB81");

            entity.HasIndex(e => e.Name, "UQ__DealType__737584F66F9FCF85").IsUnique();

            entity.Property(e => e.DealTypeId).HasColumnName("DealTypeID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__Employee__7AD04FF19854B5B2");

            entity.HasIndex(e => e.UserId, "IX_Employees_UserID");

            entity.HasIndex(e => e.UserId, "UQ__Employee__1788CCAD63E44C58").IsUnique();

            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedByUserId).HasColumnName("CreatedByUserID");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.Position).HasMaxLength(50);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.EmployeeCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Employees_CreatedBy");

            entity.HasOne(d => d.User).WithOne(p => p.EmployeeUser)
                .HasForeignKey<Employee>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employees_User");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E320EFFB9B6");

            entity.HasIndex(e => e.UserId, "IX_Notifications_UserID");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Message).HasMaxLength(500);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Type).HasMaxLength(50);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_User");
        });

        modelBuilder.Entity<Property>(entity =>
        {
            entity.HasKey(e => e.PropertyId).HasName("PK__Properti__70C9A755490F3A2B");

            entity.HasIndex(e => e.Address, "IX_Properties_Address").HasFilter("([IsDeleted]=(0))");

            entity.HasIndex(e => e.Price, "IX_Properties_Price").HasFilter("([IsDeleted]=(0))");

            entity.HasIndex(e => e.PropertyStatusId, "IX_Properties_Status");

            entity.HasIndex(e => e.PropertyTypeId, "IX_Properties_Type");

            entity.HasIndex(e => e.WallMaterialId, "IX_Properties_WallMaterial");

            entity.Property(e => e.PropertyId).HasColumnName("PropertyID");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedByUserId).HasColumnName("CreatedByUserID");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.LivingArea).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Price).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.PropertyStatusId)
                .HasDefaultValue((byte)1)
                .HasColumnName("PropertyStatusID");
            entity.Property(e => e.PropertyTypeId).HasColumnName("PropertyTypeID");
            entity.Property(e => e.TotalArea).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.WallMaterialId).HasColumnName("WallMaterialID");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Properties)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Properties_CreatedBy");

            entity.HasOne(d => d.PropertyStatus).WithMany(p => p.Properties)
                .HasForeignKey(d => d.PropertyStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Properties_Status");

            entity.HasOne(d => d.PropertyType).WithMany(p => p.Properties)
                .HasForeignKey(d => d.PropertyTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Properties_Type");

            entity.HasOne(d => d.WallMaterial).WithMany(p => p.Properties)
                .HasForeignKey(d => d.WallMaterialId)
                .HasConstraintName("FK_Properties_WallMaterial");
        });

        modelBuilder.Entity<PropertyOwner>(entity =>
        {
            entity.HasKey(e => new { e.PropertyId, e.ClientId });

            entity.Property(e => e.PropertyId).HasColumnName("PropertyID");
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedByUserId).HasColumnName("CreatedByUserID");
            entity.Property(e => e.OwnershipDocument).HasMaxLength(255);
            entity.Property(e => e.SharePercent).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Client).WithMany(p => p.PropertyOwners)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PropertyOwners_Client");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.PropertyOwners)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PropertyOwners_CreatedBy");

            entity.HasOne(d => d.Property).WithMany(p => p.PropertyOwners)
                .HasForeignKey(d => d.PropertyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PropertyOwners_Property");
        });

        modelBuilder.Entity<PropertyPhoto>(entity =>
        {
            entity.HasKey(e => e.PhotoId).HasName("PK__Property__21B7B58246BE7D6F");

            entity.HasIndex(e => e.PropertyId, "IX_PropertyPhotos_PropertyID");

            entity.Property(e => e.PhotoId).HasColumnName("PhotoID");
            entity.Property(e => e.PhotoUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("PhotoURL");
            entity.Property(e => e.PropertyId).HasColumnName("PropertyID");
            entity.Property(e => e.UploadDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UploadedByUserId).HasColumnName("UploadedByUserID");

            entity.HasOne(d => d.Property).WithMany(p => p.PropertyPhotos)
                .HasForeignKey(d => d.PropertyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Photos_Property");

            entity.HasOne(d => d.UploadedByUser).WithMany(p => p.PropertyPhotos)
                .HasForeignKey(d => d.UploadedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Photos_User");
        });

        modelBuilder.Entity<PropertyStatus>(entity =>
        {
            entity.HasKey(e => e.PropertyStatusId).HasName("PK__Property__A255202BD3F3374C");

            entity.HasIndex(e => e.StatusName, "UQ__Property__05E7698A327266F8").IsUnique();

            entity.Property(e => e.PropertyStatusId).HasColumnName("PropertyStatusID");
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<PropertyType>(entity =>
        {
            entity.HasKey(e => e.PropertyTypeId).HasName("PK__Property__BDE14DD43839168E");

            entity.HasIndex(e => e.Name, "UQ__Property__737584F6B4C461A4").IsUnique();

            entity.Property(e => e.PropertyTypeId).HasColumnName("PropertyTypeID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Showing>(entity =>
        {
            entity.HasKey(e => e.ShowingId).HasName("PK__Showings__995FC057FFA81678");

            entity.HasIndex(e => e.ClientId, "IX_Showings_ClientID");

            entity.HasIndex(e => e.PropertyId, "IX_Showings_PropertyID");

            entity.HasIndex(e => e.RealtorId, "IX_Showings_RealtorID");

            entity.Property(e => e.ShowingId).HasColumnName("ShowingID");
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.Comments).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedByUserId).HasColumnName("CreatedByUserID");
            entity.Property(e => e.PropertyId).HasColumnName("PropertyID");
            entity.Property(e => e.RealtorId).HasColumnName("RealtorID");
            entity.Property(e => e.ShowingResultId).HasColumnName("ShowingResultID");

            entity.HasOne(d => d.Client).WithMany(p => p.Showings)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Showings_Client");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Showings)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Showings_CreatedBy");

            entity.HasOne(d => d.Property).WithMany(p => p.Showings)
                .HasForeignKey(d => d.PropertyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Showings_Property");

            entity.HasOne(d => d.Realtor).WithMany(p => p.Showings)
                .HasForeignKey(d => d.RealtorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Showings_Realtor");

            entity.HasOne(d => d.ShowingResult).WithMany(p => p.Showings)
                .HasForeignKey(d => d.ShowingResultId)
                .HasConstraintName("FK_Showings_Result");
        });

        modelBuilder.Entity<ShowingResult>(entity =>
        {
            entity.HasKey(e => e.ShowingResultId).HasName("PK__ShowingR__006EAFE65A1CA5F5");

            entity.HasIndex(e => e.ResultName, "UQ__ShowingR__E5C837949B8FFC29").IsUnique();

            entity.Property(e => e.ShowingResultId).HasColumnName("ShowingResultID");
            entity.Property(e => e.ResultName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC45A6B287");

            entity.HasIndex(e => e.RoleId, "IX_Users_RoleID");

            entity.HasIndex(e => e.Login, "UQ__Users__5E55825BAB07E588").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedByUserId).HasColumnName("CreatedByUserID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.PasswordSalt)
                .IsRequired()
                .HasMaxLength(32);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.InverseCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Users_CreatedBy");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_Role");
        });

        modelBuilder.Entity<UserNotificationSetting>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__UserNoti__1788CCACE6CBC4D6");

            entity.Property(e => e.UserId)
                .ValueGeneratedNever()
                .HasColumnName("UserID");
            entity.Property(e => e.EmailForDeals).HasDefaultValue(true);
            entity.Property(e => e.EmailForShowings).HasDefaultValue(true);
            entity.Property(e => e.EmailForSystem).HasDefaultValue(true);
            entity.Property(e => e.ReceiveEmail).HasDefaultValue(true);
            entity.Property(e => e.ReceiveInApp).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithOne(p => p.UserNotificationSetting)
                .HasForeignKey<UserNotificationSetting>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Settings_User");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__UserRole__8AFACE3A4691A347");

            entity.HasIndex(e => e.RoleName, "UQ__UserRole__8A2B61609823ADF6").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<WallMaterial>(entity =>
        {
            entity.HasKey(e => e.WallMaterialId).HasName("PK__WallMate__AECA7C72E5BFCCD8");

            entity.HasIndex(e => e.Name, "UQ__WallMate__737584F6D668A76E").IsUnique();

            entity.Property(e => e.WallMaterialId).HasColumnName("WallMaterialID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}