// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class Client
{
    public int ClientId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string PassportData { get; set; }

    public string Preferences { get; set; }

    public int? UserId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CreatedByUserId { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<Deal> DealBuyers { get; set; } = new List<Deal>();

    public virtual ICollection<Deal> DealSellers { get; set; } = new List<Deal>();

    public virtual ICollection<PropertyOwner> PropertyOwners { get; set; } = new List<PropertyOwner>();

    public virtual ICollection<Showing> Showings { get; set; } = new List<Showing>();

    public virtual User User { get; set; }
}