// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class DealStatus
{
    public byte DealStatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Deal> Deals { get; set; } = new List<Deal>();
}