// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class DealDocument
{
    public int DocumentId { get; set; }

    public int DealId { get; set; }

    public string DocumentName { get; set; }

    public string FilePath { get; set; }

    public DateTime UploadDate { get; set; }

    public int UploadedByUserId { get; set; }

    public virtual Deal Deal { get; set; }

    public virtual User UploadedByUser { get; set; }
}