// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class Deal
{
    public int DealId { get; set; }

    public int PropertyId { get; set; }

    public int SellerId { get; set; }

    public int BuyerId { get; set; }

    public int RealtorId { get; set; }

    public int DealTypeId { get; set; }

    public DateTime DealDate { get; set; }

    public decimal Amount { get; set; }

    public decimal? Commission { get; set; }

    public byte DealStatusId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int CreatedByUserId { get; set; }

    public virtual Client Buyer { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<DealDocument> DealDocuments { get; set; } = new List<DealDocument>();

    public virtual DealStatus DealStatus { get; set; }

    public virtual DealType DealType { get; set; }

    public virtual Property Property { get; set; }

    public virtual Employee Realtor { get; set; }

    public virtual Client Seller { get; set; }
}