// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AgencyRealEstate.API.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AgencyRealEstate.API.Data.Models
{
    public partial interface IAppDbContextProcedures
    {
        Task<int> usp_CreateUserAsync(string login, string password, string email, byte? roleID, int? createdByUserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
