// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class PropertyOwner
{
    public int PropertyId { get; set; }

    public int ClientId { get; set; }

    public decimal? SharePercent { get; set; }

    public string OwnershipDocument { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedByUserId { get; set; }

    public virtual Client Client { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Property Property { get; set; }
}