// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class PropertyPhoto
{
    public int PhotoId { get; set; }

    public int PropertyId { get; set; }

    public string PhotoUrl { get; set; }

    public bool IsMain { get; set; }

    public DateTime UploadDate { get; set; }

    public int UploadedByUserId { get; set; }

    public virtual Property Property { get; set; }

    public virtual User UploadedByUser { get; set; }
}