// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class Property
{
    public int PropertyId { get; set; }

    public string Address { get; set; }

    public int PropertyTypeId { get; set; }

    public decimal? TotalArea { get; set; }

    public decimal? LivingArea { get; set; }

    public int? Floor { get; set; }
    public string? Title { get; set; }
    public int? Bathrooms { get; set; }

    public int? TotalFloors { get; set; }

    public int? Rooms { get; set; }

    public int? WallMaterialId { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public byte PropertyStatusId { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int CreatedByUserId { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<Deal> Deals { get; set; } = new List<Deal>();

    public virtual ICollection<PropertyOwner> PropertyOwners { get; set; } = new List<PropertyOwner>();

    public virtual ICollection<PropertyPhoto> PropertyPhotos { get; set; } = new List<PropertyPhoto>();

    public virtual PropertyStatus PropertyStatus { get; set; }

    public virtual PropertyType PropertyType { get; set; }

    public virtual ICollection<Showing> Showings { get; set; } = new List<Showing>();

    public virtual WallMaterial WallMaterial { get; set; }
}