// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class ShowingResult
{
    public byte ShowingResultId { get; set; }

    public string ResultName { get; set; }

    public virtual ICollection<Showing> Showings { get; set; } = new List<Showing>();
}