// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class Showing
{
    public int ShowingId { get; set; }

    public int PropertyId { get; set; }

    public int ClientId { get; set; }

    public int? RealtorId { get; set; }

    public DateTime ShowingDateTime { get; set; }

    public byte? ShowingResultId { get; set; }

    public string Comments { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedByUserId { get; set; }

    public virtual Client Client { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Property Property { get; set; }

    public virtual Employee Realtor { get; set; }

    public virtual ShowingResult ShowingResult { get; set; }
}