// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Login { get; set; }

    public byte[] PasswordSalt { get; set; }

    public byte[] PasswordHash { get; set; }
    public string? Position { get; set; }
    public string? Bio { get; set; }
    public string? AvatarUrl { get; set; }

    public byte RoleId { get; set; }

    public string Email { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CreatedByUserId { get; set; }

    public virtual ICollection<Client> ClientCreatedByUsers { get; set; } = new List<Client>();

    public virtual ICollection<Client> ClientUsers { get; set; } = new List<Client>();

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<DealDocument> DealDocuments { get; set; } = new List<DealDocument>();

    public virtual ICollection<Deal> Deals { get; set; } = new List<Deal>();

    public virtual ICollection<Employee> EmployeeCreatedByUsers { get; set; } = new List<Employee>();

    public virtual Employee EmployeeUser { get; set; }

    public virtual ICollection<User> InverseCreatedByUser { get; set; } = new List<User>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();

    public virtual ICollection<PropertyOwner> PropertyOwners { get; set; } = new List<PropertyOwner>();

    public virtual ICollection<PropertyPhoto> PropertyPhotos { get; set; } = new List<PropertyPhoto>();

    public virtual UserRole Role { get; set; }

    public virtual ICollection<Showing> Showings { get; set; } = new List<Showing>();

    public virtual UserNotificationSetting UserNotificationSetting { get; set; }
}