// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class UserNotificationSetting
{
    public int UserId { get; set; }

    public bool ReceiveEmail { get; set; }

    public bool ReceiveInApp { get; set; }

    public bool EmailForDeals { get; set; }

    public bool EmailForShowings { get; set; }

    public bool EmailForSystem { get; set; }

    public virtual User User { get; set; }
}