// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AgencyRealEstate.API.Data.Models;

public partial class WallMaterial
{
    public int WallMaterialId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();
}